Feature events
matheus-fls/private-events pull request #1
Opened 2019-10-10 22:48 UTC by matheus-fls

Requesting code review. Any feedback is welcome, just please be specific.

2019-10-11 16:04 UTC, AnthonyTC89 submitted a review, later dismissed

2019-10-12 15:10 UTC, efrapp requested changes
### Hey team! 👋 

Great effort so far guys. We need to make some adjustments to complete the project. Please check my comments below.

**Required changes**
- [x] `upcoming` and `past` scopes should be in the Event model
- [x] Please check this error: #2
- [x] events table has `creator_id` as the foreign key. Currently, you are using `user_id`

Please, send a new code review with the changes.

**Status:** `Changes required`

2019-10-12 15:10 UTC, efrapp commented on app/models/event.rb
> +  end
`[Optional]` I think the name should be `past_event`

2019-10-12 15:10 UTC, efrapp commented on app/models/attendance.rb
> +end
This should be placed in the Event model. You will see the query will be simpler there.

2019-10-12 15:10 UTC, efrapp commented on app/models/event.rb
> +  end
Also, I got an error in line `16`. Check #2

2019-10-12 15:10 UTC, efrapp commented on app/models/user.rb
> +  has_many :events
With the migration to create `creator_id` as the foreign key (instead of `user_id`), you need to modify this line to specify the new  `foreign_key`.

2019-10-12 15:10 UTC, efrapp commented on app/models/user.rb
> +  has_many :attendances
To build associations like "get attended events of a user" or "get attendees for a specific event" in this project, you have 2 options: use `has_many through` association or `has_many_and_belongs_to`. So, please, use one of them.

2019-10-12 15:10 UTC, efrapp commented on app/controllers/users_controller.rb
> +      @eves = Attendance.where('user_id = ?', @user.id)
Where do you use this `@eves` variable? I don't see it in the index action. Please, remove it if you don't need it.

2019-10-12 15:10 UTC, efrapp commented on app/controllers/users_controller.rb
> +      @prev_events = Attendance.past_events(@user.id)
When you create the associations I mentioned in the User model's suggestion. You will benefit from them here. For example, you will be able to do: `@user.ettended_events`.

2019-10-12 15:10 UTC, efrapp commented on app/models/event.rb
> +  has_many :attendees, class_name: 'User', through: :attendances
Here is the same as I mentioned in the User model: you should use `has_many :through` associations or `has_many_and_belongs_to` method.

2019-10-12 15:10 UTC, efrapp commented on app/controllers/events_controller.rb
> +    @events = Event.all
Here you should split it in past and upcoming events.

2019-10-14 17:19 UTC, matheus-fls commented
Hello Efrain, thank you very much for your detailed review. 

I believe we have addressed your requests, so we are submitting the code for another review.

If we missed anything, please let us know.

2019-10-15 01:46 UTC, bellom approved these changes
Hi Team,
**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in your next milestone :slightly_smiling_face:_

2019-10-15 15:18 UTC, merged